local GameConfig = {
	Phase = "11-audio-polish",
	BuildVersion = "0.1.1-audio-private",
	BuildName = "FEED THE VOID Audio Private Test",
	LaunchMode = "PrivateTest",
	DataVersion = 5,
	ProfileStoreName = "FeedTheVoid_Phase5_v2",
	StartingCoins = 150,
	StartingSeeds = {
		CookieRock = 3,
		MoonMarshmallow = 1,
	},
	EarlyGameFastPacing = true,
	MaxPlayersPerServerTarget = 8,
	PlateCount = 6,
	MaxPlateCount = 10,
	BaseDisplayIncomeInterval = 10,
	VoidHungerRequired = 100,
	VoidHungerBase = 100,
	VoidHungerPerPlayer = 35,
	TargetFirstEventSeconds = 300,
	FallResetY = -45,
	OwnerSignMaxNameLength = 14,
	RebirthRequirement = 5000,
	RebirthCost = 5000,
	RebirthKeepsCollections = true,
	RebirthKeepsStats = true,
	RebirthBoostPerRebirth = 0.15,
	OfflineGrowthMaxSeconds = 8 * 60 * 60,
	OfflineIncomeMaxSeconds = 2 * 60 * 60,
	ValuableItemConfirmRarity = "Epic",
	ValuableItemConfirmValue = 5000,
	RemoteCooldown = 0.25,
	RemoteCooldowns = {
		RequestPlantSnack = 0.5,
		RequestHarvestSnack = 0.5,
		RequestClearVoidmite = 0.25,
		RequestBuySeed = 0.35,
		RequestBuyUpgrade = 0.35,
		RequestFeedVoid = 0.35,
		RequestSellSnack = 0.35,
		RequestDisplaySnack = 0.35,
		RequestToggleItemLock = 0.25,
		RequestClaimCollectionMilestone = 0.5,
		RequestRebirth = 2,
		RequestSubmitFeedback = 30,
		RequestSkipTutorial = 1,
		RequestDebugCommand = 0.5,
		RequestClaimPlaytimeReward = 0.5,
		RequestClaimDailyReward = 0.75,
		RequestCatchPhantomSnack = 0.15,
		RequestUpdateSettings = 0.4,
		RequestCollectEventPickup = 0.15,
		RequestTeleportToPlot = 1,
	},
	RemotePayloadLimit = 8,
	AntiExploit = {
		MaxDistancePadding = 4,
		MaxInventoryItems = 140,
		MaxDisplayedSnacks = 40,
		MaxPlantedSnacks = 10,
		MaxSeedsPerType = 999,
		RemoteStrikeLimit = 8,
		RemoteStrikeWindowSeconds = 60,
	},
	SoftLaunch = {
		HealthCheckOnServerStart = true,
		ActivityFeedEnabled = true,
		AllowDebugInStudio = true,
		AllowDataResetInStudio = true,
		RequireOwnerForDebugOutsideStudio = true,
	},
	MaxVoidmitesPerPlot = 8,
	BaseVoidmiteSpawnInterval = 14,
	MinVoidmiteSpawnInterval = 6,
	FirstVoidmiteSpawnDelay = 45,
	PlaytimeRewards = {
		{ Seconds = 120, Coins = 50, Label = "2 min: 50 Coins" },
		{ Seconds = 300, Seeds = { JellyCube = 1 }, Label = "5 min: Jelly Cube seed" },
		{ Seconds = 600, Coins = 150, VoidTokens = 2, Label = "10 min: 150 Coins + 2 Void Tokens" },
		{ Seconds = 1200, Seeds = { MeteorMuffin = 1 }, Label = "20 min: Meteor Muffin seed" },
		{ Seconds = 1800, Coins = 500, VoidTokens = 5, Label = "30 min: 500 Coins + 5 Void Tokens" },
	},
	DailyRewardCooldownSeconds = 20 * 60 * 60,
	DailyRewardStreakGraceSeconds = 48 * 60 * 60,
	ShopRestockInterval = 5 * 60,
	ShopAlwaysAvailableSeeds = { "CookieRock", "MoonMarshmallow", "BubbleBread" },
	ShopRotatingSeeds = {
		"JellyCube",
		"SlimePretzel",
		"NeonToast",
		"MeteorMuffin",
		"CrystalDonut",
		"StarPancake",
		"LavaNoodleWrap",
		"VoidWaffle",
		"BlackHoleBurrito",
		"GoldenFridgeSnack",
	},
	SettingsDefaults = {
		ReduceEffects = false,
		LowDetailMode = false,
		MuteSounds = false,
		HideExtraPopups = false,
		AutoClosePanels = true,
		ShowGuidance = true,
	},
	Performance = {
		EventCountdownSyncInterval = 1,
		VoidmiteSpawnScanInterval = 8,
		FailsafeCheckInterval = 10,
		PlaytimeCheckInterval = 8,
		ShopRestockPollInterval = 10,
		MaxEventPickups = 60,
		MaxPhantoms = 5,
		MaxVoidmitesGlobal = 80,
	},
	Limits = {
		MaxVoidmitesPerPlot = 8,
		MaxVoidmitesGlobal = 80,
		MaxSnackRainPickups = 60,
		MaxPhantomSnacks = 5,
		MaxDisplayedSnacksPerPlayer = 10,
		MaxInventoryItems = 250,
		MaxActiveSnacksPerPlayer = 10,
		MaxNotificationsQueued = 5,
	},
	Security = {
		InvalidRemoteWarnThreshold = 5,
		InvalidRemoteWindowSeconds = 10,
		TemporaryIgnoreSeconds = 5,
	},
	InteractionDistances = {
		Plate = 12,
		Harvest = 12,
		Display = 15,
		VoidFeed = 25,
		Voidmite = 12,
		Phantom = 14,
		Pickup = 10,
		Shop = 18,
		Daily = 18,
		Rebirth = 18,
		Teleport = 24,
	},
	PrivateTest = {
		MaxPlayers = 8,
		EnableFeedbackButton = true,
		EnableFunnelLogs = true,
		ShowDebugWatermark = true,
		FeedbackSaveToDataStore = false,
		KickUnlistedPlayers = false,
		KickMessage = "FEED THE VOID is in private testing right now.",
	},
	Failsafes = {
		CheckInterval = 10,
		EmergencySeedId = "CookieRock",
		EmergencySeedAmount = 1,
		EmergencySeedCooldown = 120,
		TeleportToPlotCooldown = 15,
		ReadySnackHintCooldown = 25,
		FullPlatesHintCooldown = 25,
	},
	CollectionMilestones = {
		{ Id = "SnackTypes3", Text = "Discover 3 snack types", Kind = "SnackTypes", Target = 3, Coins = 100 },
		{ Id = "SnackTypes5", Text = "Discover 5 snack types", Kind = "SnackTypes", Target = 5, Coins = 250 },
		{ Id = "SnackTypes10", Text = "Discover 10 snack types", Kind = "SnackTypes", Target = 10, Coins = 750 },
		{ Id = "AllCommonSnacks", Text = "Discover all Common snacks", Kind = "AllRarity", Rarity = "Common", Seeds = { JellyCube = 1 } },
		{ Id = "AllUncommonSnacks", Text = "Discover all Uncommon snacks", Kind = "AllRarity", Rarity = "Uncommon", VoidTokens = 3 },
		{ Id = "Mutations5", Text = "Discover 5 mutations", Kind = "Mutations", Target = 5, Coins = 500 },
		{ Id = "Combos10", Text = "Discover 10 combos", Kind = "Combos", Target = 10, VoidTokens = 5 },
		{ Id = "Combos25", Text = "Discover 25 combos", Kind = "Combos", Target = 25, Coins = 1500, VoidTokens = 10 },
		{ Id = "FirstVoidTouched", Text = "Discover Void Touched", Kind = "Mutation", MutationId = "VoidTouched", Coins = 500, VoidTokens = 3, Announce = true },
		{ Id = "FirstGlitched", Text = "Discover Glitched", Kind = "Mutation", MutationId = "Glitched", Coins = 1000, VoidTokens = 5, Announce = true },
	},
	ActivityFeed = {
		Enabled = true,
		MinSecondsBetweenMessages = 4,
		RareMutationMinimumValueMultiplier = 2,
		EpicSnackMinimumRarity = "Epic",
		RareFeedMinimumRarity = "Rare",
	},
	BadgeConfig = {
		FirstSnackHarvested = 0,
		FirstVoidFeed = 0,
		FirstVoidEvent = 0,
		FirstVoidmiteCleanse = 0,
		FirstRebirth = 0,
		FirstVoidTouched = 0,
		TenDiscoveries = 0,
		HundredSnacksFed = 0,
	},
	SoundConfigVersion = "Phase11",
	DebugOwnerUserIds = {},
	PrivateTestUserIds = {},
	PrivateTestGroupId = 0,
	DebugMode = true,
	DebugFastGrowth = false,
	DebugFastVoid = false,
	DebugGiveCoins = true,
	DebugShortEvents = false,
	FastGrowthTime = 6,
	FastVoidHungerRequired = 30,
	TestOverrideDefaults = {
		HungerRequired = nil,
		GrowMultiplier = 1,
		VoidmiteSpeedMultiplier = 1,
	},
	UpgradeOrder = {
		"ExtraPlate",
		"GrowSpeed",
		"SellMultiplier",
		"VoidRewardMultiplier",
		"DisplayIncome",
		"VoidmiteReward",
	},
	UpgradeConfig = {
		ExtraPlate = {
			DisplayName = "Extra Plate",
			BaseCost = 90,
			MaxLevel = 4,
			Kind = "Plate",
			Description = "Unlock one more grow plate.",
		},
		GrowSpeed = {
			DisplayName = "Grow Speed",
			BaseCost = 75,
			MaxLevel = 10,
			PerLevel = 0.05,
			Description = "+5% grow speed per level.",
		},
		SellMultiplier = {
			DisplayName = "Sell Multiplier",
			BaseCost = 90,
			MaxLevel = 10,
			PerLevel = 0.10,
			Description = "+10% sell value per level.",
		},
		VoidRewardMultiplier = {
			DisplayName = "Void Reward",
			BaseCost = 95,
			MaxLevel = 10,
			PerLevel = 0.10,
			Description = "+10% Void rewards per level.",
		},
		DisplayIncome = {
			DisplayName = "Display Income",
			BaseCost = 85,
			MaxLevel = 10,
			PerLevel = 0.10,
			Description = "+10% passive income per level.",
		},
		VoidmiteReward = {
			DisplayName = "Voidmite Reward",
			BaseCost = 85,
			MaxLevel = 10,
			PerLevel = 0.10,
			Description = "+10% cleanse rewards per level.",
		},
	},
	TutorialMessages = {
		"Welcome to FEED THE VOID.",
		"Follow the guide to your lab and plant a seed.",
		"Wait for the snack to grow above the plate.",
		"Harvest the ready snack.",
		"Feed a snack to The Void.",
		"Display a snack on your shelf for passive coins.",
		"Cleanse a Voidmite when one appears.",
		"Buy your first useful upgrade.",
		"Complete objectives for extra rewards.",
		"Keep feeding The Void to start server events.",
	},
}

return GameConfig
