local SnackConfig = {
	CookieRock = {
		DisplayName = "Cookie Rock",
		Rarity = "Common",
		VisualType = "Round",
		SeedCost = 10,
		GrowTime = 14,
		BaseSellValue = 25,
		BaseVoidValue = 10,
		UnlockRequirement = "Starter",
		SortOrder = 1,
		ThemeColor = Color3.fromRGB(185, 164, 132),
		Color = Color3.fromRGB(185, 164, 132),
		Buyable = true,
	},
	MoonMarshmallow = {
		DisplayName = "Moon Marshmallow",
		Rarity = "Common",
		VisualType = "Round",
		SeedCost = 15,
		GrowTime = 20,
		BaseSellValue = 40,
		BaseVoidValue = 14,
		UnlockRequirement = "Starter",
		SortOrder = 2,
		ThemeColor = Color3.fromRGB(220, 224, 255),
		Color = Color3.fromRGB(220, 224, 255),
		Buyable = true,
	},
	BubbleBread = {
		DisplayName = "Bubble Bread",
		Rarity = "Common",
		VisualType = "Wrap",
		SeedCost = 25,
		GrowTime = 25,
		BaseSellValue = 65,
		BaseVoidValue = 20,
		UnlockRequirement = "Starter",
		SortOrder = 3,
		ThemeColor = Color3.fromRGB(255, 158, 204),
		Color = Color3.fromRGB(255, 158, 204),
		Buyable = true,
	},
	JellyCube = {
		DisplayName = "Jelly Cube",
		Rarity = "Uncommon",
		VisualType = "Cube",
		SeedCost = 35,
		GrowTime = 28,
		BaseSellValue = 90,
		BaseVoidValue = 30,
		UnlockRequirement = "Harvest 3 snacks or complete 1 quest",
		SortOrder = 10,
		ThemeColor = Color3.fromRGB(92, 220, 225),
		Color = Color3.fromRGB(92, 220, 225),
		Buyable = true,
	},
	SlimePretzel = {
		DisplayName = "Slime Pretzel",
		Rarity = "Uncommon",
		VisualType = "Wrap",
		SeedCost = 60,
		GrowTime = 35,
		BaseSellValue = 150,
		BaseVoidValue = 45,
		UnlockRequirement = "Harvest 3 snacks or complete 1 quest",
		SortOrder = 11,
		ThemeColor = Color3.fromRGB(120, 225, 116),
		Color = Color3.fromRGB(120, 225, 116),
		Buyable = true,
	},
	NeonToast = {
		DisplayName = "Neon Toast",
		Rarity = "Uncommon",
		VisualType = "Round",
		SeedCost = 85,
		GrowTime = 40,
		BaseSellValue = 230,
		BaseVoidValue = 60,
		UnlockRequirement = "Harvest 3 snacks or complete 1 quest",
		SortOrder = 12,
		ThemeColor = Color3.fromRGB(255, 218, 92),
		Color = Color3.fromRGB(255, 218, 92),
		Buyable = true,
	},
	MeteorMuffin = {
		DisplayName = "Meteor Muffin",
		Rarity = "Rare",
		VisualType = "Round",
		AssetKey = "SnackMeteorMuffin",
		SeedCost = 150,
		GrowTime = 55,
		BaseSellValue = 450,
		BaseVoidValue = 110,
		UnlockRequirement = "Harvest 10 snacks, discover 5 snacks, or reach Rebirth 1",
		SortOrder = 20,
		ThemeColor = Color3.fromRGB(220, 92, 76),
		Color = Color3.fromRGB(220, 92, 76),
		Buyable = true,
	},
	CrystalDonut = {
		DisplayName = "Crystal Donut",
		Rarity = "Rare",
		VisualType = "Round",
		AssetKey = "SnackCrystalDonut",
		SeedCost = 250,
		GrowTime = 75,
		BaseSellValue = 750,
		BaseVoidValue = 170,
		UnlockRequirement = "Harvest 10 snacks, discover 5 snacks, or reach Rebirth 1",
		SortOrder = 21,
		ThemeColor = Color3.fromRGB(119, 218, 255),
		Color = Color3.fromRGB(119, 218, 255),
		Buyable = true,
	},
	GoblinSandwich = {
		DisplayName = "Goblin Sandwich",
		Rarity = "Rare",
		VisualType = "Wrap",
		AssetKey = "SnackGoblinSandwich",
		SeedCost = 375,
		GrowTime = 90,
		BaseSellValue = 1100,
		BaseVoidValue = 250,
		UnlockRequirement = "Harvest 10 snacks, discover 5 snacks, or reach Rebirth 1",
		SortOrder = 22,
		ThemeColor = Color3.fromRGB(130, 190, 96),
		Color = Color3.fromRGB(130, 190, 96),
		Buyable = true,
	},
	StarPancake = {
		DisplayName = "Star Pancake",
		Rarity = "Epic",
		VisualType = "Round",
		AssetKey = "SnackStarPancake",
		SeedCost = 700,
		GrowTime = 120,
		BaseSellValue = 2200,
		BaseVoidValue = 450,
		UnlockRequirement = "Reach Rebirth 1 or make 25 discoveries",
		SortOrder = 30,
		ThemeColor = Color3.fromRGB(255, 212, 116),
		Color = Color3.fromRGB(255, 212, 116),
		Buyable = true,
	},
	LavaNoodleWrap = {
		DisplayName = "Lava Noodle Wrap",
		Rarity = "Epic",
		VisualType = "Wrap",
		AssetKey = "SnackLavaNoodleWrap",
		SeedCost = 1000,
		GrowTime = 150,
		BaseSellValue = 3500,
		BaseVoidValue = 650,
		UnlockRequirement = "Reach Rebirth 1 or make 25 discoveries",
		SortOrder = 31,
		ThemeColor = Color3.fromRGB(255, 97, 48),
		Color = Color3.fromRGB(255, 97, 48),
		Buyable = true,
	},
	VoidWaffle = {
		DisplayName = "Void Waffle",
		Rarity = "Epic",
		VisualType = "Cube",
		AssetKey = "SnackVoidWaffle",
		SeedCost = 1500,
		GrowTime = 180,
		BaseSellValue = 5200,
		BaseVoidValue = 900,
		UnlockRequirement = "Reach Rebirth 1 or make 25 discoveries",
		SortOrder = 32,
		ThemeColor = Color3.fromRGB(110, 76, 160),
		Color = Color3.fromRGB(110, 76, 160),
		Buyable = true,
	},
	BlackHoleBurrito = {
		DisplayName = "Black Hole Burrito",
		Rarity = "Legendary",
		VisualType = "Wrap",
		AssetKey = "SnackBlackHoleBurrito",
		SeedCost = 3500,
		GrowTime = 240,
		BaseSellValue = 12000,
		BaseVoidValue = 1800,
		UnlockRequirement = "Reach Rebirth 2 or make 50 discoveries",
		SortOrder = 40,
		ThemeColor = Color3.fromRGB(48, 31, 70),
		Color = Color3.fromRGB(48, 31, 70),
		Buyable = true,
	},
	GoldenFridgeSnack = {
		DisplayName = "Golden Fridge Snack",
		Rarity = "Legendary",
		VisualType = "Cube",
		AssetKey = "SnackGoldenFridgeSnack",
		SeedCost = 5000,
		GrowTime = 300,
		BaseSellValue = 18000,
		BaseVoidValue = 2500,
		UnlockRequirement = "Reach Rebirth 2 or make 50 discoveries",
		SortOrder = 41,
		ThemeColor = Color3.fromRGB(255, 205, 58),
		Color = Color3.fromRGB(255, 205, 58),
		Buyable = true,
	},
	LivingSandwich = {
		DisplayName = "Living Sandwich",
		Rarity = "Secret",
		VisualType = "Wrap",
		AssetKey = "SnackLivingSandwich",
		SeedCost = nil,
		GrowTime = 420,
		BaseSellValue = 50000,
		BaseVoidValue = 7500,
		UnlockRequirement = "Secret reward only",
		SortOrder = 50,
		ThemeColor = Color3.fromRGB(190, 255, 175),
		Color = Color3.fromRGB(190, 255, 175),
		Buyable = false,
		Locked = true,
	},
}

SnackConfig.Order = {
	"CookieRock",
	"MoonMarshmallow",
	"BubbleBread",
	"JellyCube",
	"SlimePretzel",
	"NeonToast",
	"MeteorMuffin",
	"CrystalDonut",
	"GoblinSandwich",
	"StarPancake",
	"LavaNoodleWrap",
	"VoidWaffle",
	"BlackHoleBurrito",
	"GoldenFridgeSnack",
	"LivingSandwich",
}

SnackConfig.StageScale = {
	[1] = 0.34,
	[2] = 0.62,
	[3] = 0.92,
}

SnackConfig.GrowthLift = {
	[1] = 0.42,
	[2] = 0.82,
	[3] = 1.18,
}

SnackConfig.RarityMaxSize = {
	Common = 2.2,
	Uncommon = 2.5,
	Rare = 2.9,
	Epic = 3.25,
	Legendary = 3.6,
	Secret = 3.8,
}

SnackConfig.VisualTypeSizeScale = {
	Round = 1,
	Cube = 0.9,
	Wrap = 1,
}

return SnackConfig
