local FTWAssetManifest = {
	Phase = "15-private-test-qa",
	Note = "Phase 15 private-test asset mapping for imported FEED THE VOID models. Runtime code should use AssetReferences keys, not raw paths.",
	LibraryRoot = "ReplicatedStorage.Assets.Models",
	DuplicatesRoot = "ReplicatedStorage.Assets.Duplicates",
	Assets = {
		FTW_TheVoid = { Key = "TheVoid", Folder = "Void", Path = "ReplicatedStorage.Assets.Models.Void.FTW_TheVoid" },
		FTW_Voidmite = { Key = "Voidmite", Folder = "Creatures", Path = "ReplicatedStorage.Assets.Models.Creatures.FTW_Voidmite" },
		FTW_VoidlingPet = { Key = "VoidlingPet", Folder = "Creatures", Path = "ReplicatedStorage.Assets.Models.Creatures.FTW_VoidlingPet" },
		FTW_SeedCapsule_Generic = { Key = "SeedCapsuleGeneric", Folder = "Seeds", Path = "ReplicatedStorage.Assets.Models.Seeds.FTW_SeedCapsule_Generic" },
		FTW_SnackSprout_Generic = { Key = "SnackSproutGeneric", Folder = "Growth", Path = "ReplicatedStorage.Assets.Models.Growth.FTW_SnackSprout_Generic" },
		FTW_SnackBud_Generic = { Key = "SnackBudGeneric", Folder = "Growth", Path = "ReplicatedStorage.Assets.Models.Growth.FTW_SnackBud_Generic" },
		FTW_Snack_RoundBase = { Key = "SnackRoundBase", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_RoundBase" },
		FTW_Snack_CubeBase = { Key = "SnackCubeBase", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_CubeBase" },
		FTW_Snack_WrapBase = { Key = "SnackWrapBase", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_WrapBase" },
		FTW_Snack_CrystalDonut = { Key = "SnackCrystalDonut", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_CrystalDonut" },
		FTW_Snack_MeteorMuffin = { Key = "SnackMeteorMuffin", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_MeteorMuffin" },
		FTW_Snack_GoblinSandwich = { Key = "SnackGoblinSandwich", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_GoblinSandwich" },
		FTW_Snack_StarPancake = { Key = "SnackStarPancake", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_StarPancake" },
		FTW_Snack_LavaNoodleWrap = { Key = "SnackLavaNoodleWrap", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_LavaNoodleWrap" },
		FTW_Snack_VoidWaffle = { Key = "SnackVoidWaffle", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_VoidWaffle" },
		FTW_Snack_BlackHoleBurrito = { Key = "SnackBlackHoleBurrito", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_BlackHoleBurrito" },
		FTW_Snack_GoldenFridgeSnack = { Key = "SnackGoldenFridgeSnack", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_GoldenFridgeSnack" },
		FTW_Snack_LivingSandwich = { Key = "SnackLivingSandwich", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_Snack_LivingSandwich" },
		FTW_PhantomSnack = { Key = "PhantomSnack", Folder = "Snacks", Path = "ReplicatedStorage.Assets.Models.Snacks.FTW_PhantomSnack" },
		FTW_GrowPlate = { Key = "GrowPlate", Folder = "Plot", Path = "ReplicatedStorage.Assets.Models.Plot.FTW_GrowPlate" },
		FTW_DisplayPedestal = { Key = "DisplayPedestal", Folder = "Plot", Path = "ReplicatedStorage.Assets.Models.Plot.FTW_DisplayPedestal" },
		FTW_SeedShopMachine = { Key = "SeedShopMachine", Folder = "Stations", Path = "ReplicatedStorage.Assets.Models.Stations.FTW_SeedShopMachine" },
		FTW_SellStation = { Key = "SellStation", Folder = "Stations", Path = "ReplicatedStorage.Assets.Models.Stations.FTW_SellStation" },
		FTW_UpgradeStation = { Key = "UpgradeStation", Folder = "Stations", Path = "ReplicatedStorage.Assets.Models.Stations.FTW_UpgradeStation" },
		FTW_RebirthPortal = { Key = "RebirthPortal", Folder = "Stations", Path = "ReplicatedStorage.Assets.Models.Stations.FTW_RebirthPortal" },
		FTW_Event_SnackRainCloud = { Key = "EventSnackRainCloud", Folder = "Events", Path = "ReplicatedStorage.Assets.Models.Events.FTW_Event_SnackRainCloud" },
		FTW_Event_MutationCrystal = { Key = "EventMutationCrystal", Folder = "Events", Path = "ReplicatedStorage.Assets.Models.Events.FTW_Event_MutationCrystal" },
		FTW_Event_VoidmiteNest = { Key = "EventVoidmiteNest", Folder = "Events", Path = "ReplicatedStorage.Assets.Models.Events.FTW_Event_VoidmiteNest" },
		FTW_Event_GoldenHungerIdol = { Key = "EventGoldenHungerIdol", Folder = "Events", Path = "ReplicatedStorage.Assets.Models.Events.FTW_Event_GoldenHungerIdol" },
		FTW_VoidCrumbPickup = { Key = "VoidCrumbPickup", Folder = "Pickups", Path = "ReplicatedStorage.Assets.Models.Pickups.FTW_VoidCrumbPickup" },
		FTW_VoidShardPickup = { Key = "VoidShardPickup", Folder = "Pickups", Path = "ReplicatedStorage.Assets.Models.Pickups.FTW_VoidShardPickup" },
		FTW_DailyRewardChest = { Key = "DailyRewardChest", Folder = "Rewards", Path = "ReplicatedStorage.Assets.Models.Rewards.FTW_DailyRewardChest" },
		FTW_PlaytimeRewardClock = { Key = "PlaytimeRewardClock", Folder = "Rewards", Path = "ReplicatedStorage.Assets.Models.Rewards.FTW_PlaytimeRewardClock" },
		FTW_CollectionBook = { Key = "CollectionBook", Folder = "Rewards", Path = "ReplicatedStorage.Assets.Models.Rewards.FTW_CollectionBook" },
	},
}

return FTWAssetManifest
